//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.31 at 10:03:34 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.cirtil.fr/sae/viPortailAportail")
package fr.urssaf.image.sae.vi.modele.jaxb.viportail;
