//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.07 at 09:57:44 AM CEST 
//


package fr.urssaf.image.sae.vi.modele.jaxb.viportail;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for viType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="viType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="issuer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="audience" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nameID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pagms" type="{http://www.cirtil.fr/sae/viPortailAportail}pagmsType"/>
 *         &lt;element name="habilitationAnais" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "viType", propOrder = {
    "issuer",
    "audience",
    "nameID",
    "pagms",
    "habilitationAnais"
})
// CHECKSTYLE:OFF
@SuppressWarnings("all")
@XmlRootElement(name="vi")
public class ViType {

    @XmlElement(required = true)
    protected String issuer;
    @XmlElement(required = true)
    protected String audience;
    @XmlElement(required = true)
    protected String nameID;
    @XmlElement(required = true)
    protected PagmsType pagms;
    @XmlElement(required = true)
    protected String habilitationAnais;

    /**
     * Gets the value of the issuer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssuer() {
        return issuer;
    }

    /**
     * Sets the value of the issuer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssuer(String value) {
        this.issuer = value;
    }

    /**
     * Gets the value of the audience property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAudience() {
        return audience;
    }

    /**
     * Sets the value of the audience property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAudience(String value) {
        this.audience = value;
    }

    /**
     * Gets the value of the nameID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameID() {
        return nameID;
    }

    /**
     * Sets the value of the nameID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameID(String value) {
        this.nameID = value;
    }

    /**
     * Gets the value of the pagms property.
     * 
     * @return
     *     possible object is
     *     {@link PagmsType }
     *     
     */
    public PagmsType getPagms() {
        return pagms;
    }

    /**
     * Sets the value of the pagms property.
     * 
     * @param value
     *     allowed object is
     *     {@link PagmsType }
     *     
     */
    public void setPagms(PagmsType value) {
        this.pagms = value;
    }

    /**
     * Gets the value of the habilitationAnais property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHabilitationAnais() {
        return habilitationAnais;
    }

    /**
     * Sets the value of the habilitationAnais property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHabilitationAnais(String value) {
        this.habilitationAnais = value;
    }

}
