
package sae.client.demo.webservice.modele;

import javax.xml.ws.WebFault;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2019-02-01T14:57:39.740+01:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "archivageUnitairePJFault", targetNamespace = "http://www.cirtil.fr/saeService")
// CHECKSTYLE:OFF
@SuppressWarnings("all")
public class ArchivageUnitairePJFault extends Exception {

   private java.lang.String archivageUnitairePJFault;

   public ArchivageUnitairePJFault() {
      super();
   }

   public ArchivageUnitairePJFault(final String message) {
      super(message);
   }

   public ArchivageUnitairePJFault(final String message, final Throwable cause) {
      super(message, cause);
   }

   public ArchivageUnitairePJFault(final String message, final java.lang.String archivageUnitairePJFault) {
      super(message);
      this.archivageUnitairePJFault = archivageUnitairePJFault;
   }

   public ArchivageUnitairePJFault(final String message, final java.lang.String archivageUnitairePJFault, final Throwable cause) {
      super(message, cause);
      this.archivageUnitairePJFault = archivageUnitairePJFault;
   }

   public java.lang.String getFaultInfo() {
      return this.archivageUnitairePJFault;
   }
}
