//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.11 at 10:45:13 AM CEST 
//


package fr.urssaf.image.sae.integration.droits.modele.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DroitType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DroitType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="listePrmd" type="{http://www.cirtil.fr/saeIntegration/droit}ListePrmdType"/>
 *         &lt;element name="listeCs" type="{http://www.cirtil.fr/saeIntegration/droit}ListeCsType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DroitType", propOrder = {
    "listePrmd",
    "listeCs"
})
// CHECKSTYLE:OFF
@SuppressWarnings("all")
public class DroitType {

    @XmlElement(required = true)
    protected ListePrmdType listePrmd;
    @XmlElement(required = true)
    protected ListeCsType listeCs;

    /**
     * Gets the value of the listePrmd property.
     * 
     * @return
     *     possible object is
     *     {@link ListePrmdType }
     *     
     */
    public ListePrmdType getListePrmd() {
        return listePrmd;
    }

    /**
     * Sets the value of the listePrmd property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListePrmdType }
     *     
     */
    public void setListePrmd(ListePrmdType value) {
        this.listePrmd = value;
    }

    /**
     * Gets the value of the listeCs property.
     * 
     * @return
     *     possible object is
     *     {@link ListeCsType }
     *     
     */
    public ListeCsType getListeCs() {
        return listeCs;
    }

    /**
     * Sets the value of the listeCs property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListeCsType }
     *     
     */
    public void setListeCs(ListeCsType value) {
        this.listeCs = value;
    }

}
