//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.19 at 02:36:29 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.cirtil.fr/saeIntegration/droit", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package fr.urssaf.image.sae.integration.droits.modele.xml;
