//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.11 at 10:45:13 AM CEST 
//


package fr.urssaf.image.sae.integration.droits.modele.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PagmType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PagmType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pagma" type="{http://www.cirtil.fr/saeIntegration/droit}PagmaType"/>
 *         &lt;element name="pagmp" type="{http://www.cirtil.fr/saeIntegration/droit}PagmpType"/>
 *         &lt;element name="parametres" type="{http://www.cirtil.fr/saeIntegration/droit}ListeParametresPagmType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PagmType", propOrder = {
    "code",
    "description",
    "pagma",
    "pagmp",
    "parametres"
})
// CHECKSTYLE:OFF
@SuppressWarnings("all")
public class PagmType {

    @XmlElement(required = true)
    protected String code;
    @XmlElement(required = true)
    protected String description;
    @XmlElement(required = true)
    protected PagmaType pagma;
    @XmlElement(required = true)
    protected PagmpType pagmp;
    @XmlElement(required = true)
    protected ListeParametresPagmType parametres;

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the pagma property.
     * 
     * @return
     *     possible object is
     *     {@link PagmaType }
     *     
     */
    public PagmaType getPagma() {
        return pagma;
    }

    /**
     * Sets the value of the pagma property.
     * 
     * @param value
     *     allowed object is
     *     {@link PagmaType }
     *     
     */
    public void setPagma(PagmaType value) {
        this.pagma = value;
    }

    /**
     * Gets the value of the pagmp property.
     * 
     * @return
     *     possible object is
     *     {@link PagmpType }
     *     
     */
    public PagmpType getPagmp() {
        return pagmp;
    }

    /**
     * Sets the value of the pagmp property.
     * 
     * @param value
     *     allowed object is
     *     {@link PagmpType }
     *     
     */
    public void setPagmp(PagmpType value) {
        this.pagmp = value;
    }

    /**
     * Gets the value of the parametres property.
     * 
     * @return
     *     possible object is
     *     {@link ListeParametresPagmType }
     *     
     */
    public ListeParametresPagmType getParametres() {
        return parametres;
    }

    /**
     * Sets the value of the parametres property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListeParametresPagmType }
     *     
     */
    public void setParametres(ListeParametresPagmType value) {
        this.parametres = value;
    }

}
