//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.27 at 10:07:17 AM CEST 
//


package fr.urssaf.image.sae.integration.ihmweb.modele.somres.commun_sommaire_et_resultat;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the fr.urssaf.image.sae.services.batch.capturemasse.modele.commun_sommaire_et_resultat package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DocumentMultiAction_QNAME = new QName("http://www.cirtil.fr/sae/commun_sommaire_et_resultat", "documentMultiAction");
    private final static QName _Document_QNAME = new QName("http://www.cirtil.fr/sae/commun_sommaire_et_resultat", "document");
    private final static QName _ObjetNumerique_QNAME = new QName("http://www.cirtil.fr/sae/commun_sommaire_et_resultat", "objetNumerique");
    private final static QName _Composant_QNAME = new QName("http://www.cirtil.fr/sae/commun_sommaire_et_resultat", "composant");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: fr.urssaf.image.sae.services.batch.capturemasse.modele.commun_sommaire_et_resultat
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DocumentType }
     * 
     */
    public DocumentType createDocumentType() {
        return new DocumentType();
    }

    /**
     * Create an instance of {@link ListeIntegratedDocumentsType }
     * 
     */
    public ListeIntegratedDocumentsType createListeIntegratedDocumentsType() {
        return new ListeIntegratedDocumentsType();
    }

    /**
     * Create an instance of {@link IntegratedDocumentType }
     * 
     */
    public IntegratedDocumentType createIntegratedDocumentType() {
        return new IntegratedDocumentType();
    }

    /**
     * Create an instance of {@link ListeMetadonneeType }
     * 
     */
    public ListeMetadonneeType createListeMetadonneeType() {
        return new ListeMetadonneeType();
    }

    /**
     * Create an instance of {@link FichierType }
     * 
     */
    public FichierType createFichierType() {
        return new FichierType();
    }

    /**
     * Create an instance of {@link ListeNonIntegratedVirtualDocumentsType }
     * 
     */
    public ListeNonIntegratedVirtualDocumentsType createListeNonIntegratedVirtualDocumentsType() {
        return new ListeNonIntegratedVirtualDocumentsType();
    }

    /**
     * Create an instance of {@link ListeNonIntegratedDocumentsType }
     * 
     */
    public ListeNonIntegratedDocumentsType createListeNonIntegratedDocumentsType() {
        return new ListeNonIntegratedDocumentsType();
    }

    /**
     * Create an instance of {@link ListeDocumentsVirtuelsType }
     * 
     */
    public ListeDocumentsVirtuelsType createListeDocumentsVirtuelsType() {
        return new ListeDocumentsVirtuelsType();
    }

    /**
     * Create an instance of {@link ComposantDocumentVirtuelType }
     * 
     */
    public ComposantDocumentVirtuelType createComposantDocumentVirtuelType() {
        return new ComposantDocumentVirtuelType();
    }

    /**
     * Create an instance of {@link IntegratedDocumentVirtuelType.Composants }
     * 
     */
    public IntegratedDocumentVirtuelType.Composants createIntegratedDocumentVirtuelTypeComposants() {
        return new IntegratedDocumentVirtuelType.Composants();
    }

    /**
     * Create an instance of {@link ListeDocumentsTypeMultiAction }
     * 
     */
    public ListeDocumentsTypeMultiAction createListeDocumentsTypeMultiAction() {
        return new ListeDocumentsTypeMultiAction();
    }

    /**
     * Create an instance of {@link MetadonneeType }
     * 
     */
    public MetadonneeType createMetadonneeType() {
        return new MetadonneeType();
    }

    /**
     * Create an instance of {@link DocumentVirtuelType }
     * 
     */
    public DocumentVirtuelType createDocumentVirtuelType() {
        return new DocumentVirtuelType();
    }

    /**
     * Create an instance of {@link ListeErreurType }
     * 
     */
    public ListeErreurType createListeErreurType() {
        return new ListeErreurType();
    }

    /**
     * Create an instance of {@link NonIntegratedVirtualDocumentType }
     * 
     */
    public NonIntegratedVirtualDocumentType createNonIntegratedVirtualDocumentType() {
        return new NonIntegratedVirtualDocumentType();
    }

    /**
     * Create an instance of {@link IntegratedDocumentVirtuelType }
     * 
     */
    public IntegratedDocumentVirtuelType createIntegratedDocumentVirtuelType() {
        return new IntegratedDocumentVirtuelType();
    }

    /**
     * Create an instance of {@link ErreurType }
     * 
     */
    public ErreurType createErreurType() {
        return new ErreurType();
    }

    /**
     * Create an instance of {@link IntegratedComposantDocumentVirtuelType }
     * 
     */
    public IntegratedComposantDocumentVirtuelType createIntegratedComposantDocumentVirtuelType() {
        return new IntegratedComposantDocumentVirtuelType();
    }

    /**
     * Create an instance of {@link ListeDocumentsType }
     * 
     */
    public ListeDocumentsType createListeDocumentsType() {
        return new ListeDocumentsType();
    }

    /**
     * Create an instance of {@link NonIntegratedComposantDocumentVirtuelType }
     * 
     */
    public NonIntegratedComposantDocumentVirtuelType createNonIntegratedComposantDocumentVirtuelType() {
        return new NonIntegratedComposantDocumentVirtuelType();
    }

    /**
     * Create an instance of {@link DocumentTypeMultiAction }
     * 
     */
    public DocumentTypeMultiAction createDocumentTypeMultiAction() {
        return new DocumentTypeMultiAction();
    }

    /**
     * Create an instance of {@link NonIntegratedDocumentType }
     * 
     */
    public NonIntegratedDocumentType createNonIntegratedDocumentType() {
        return new NonIntegratedDocumentType();
    }

    /**
     * Create an instance of {@link DocumentVirtuelType.Composants }
     * 
     */
    public DocumentVirtuelType.Composants createDocumentVirtuelTypeComposants() {
        return new DocumentVirtuelType.Composants();
    }

    /**
     * Create an instance of {@link ListeIntegratedDocumentsVirtuelsType }
     * 
     */
    public ListeIntegratedDocumentsVirtuelsType createListeIntegratedDocumentsVirtuelsType() {
        return new ListeIntegratedDocumentsVirtuelsType();
    }

    /**
     * Create an instance of {@link NonIntegratedVirtualDocumentType.Composants }
     * 
     */
    public NonIntegratedVirtualDocumentType.Composants createNonIntegratedVirtualDocumentTypeComposants() {
        return new NonIntegratedVirtualDocumentType.Composants();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DocumentTypeMultiAction }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cirtil.fr/sae/commun_sommaire_et_resultat", name = "documentMultiAction")
    public JAXBElement<DocumentTypeMultiAction> createDocumentMultiAction(DocumentTypeMultiAction value) {
        return new JAXBElement<DocumentTypeMultiAction>(_DocumentMultiAction_QNAME, DocumentTypeMultiAction.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DocumentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cirtil.fr/sae/commun_sommaire_et_resultat", name = "document")
    public JAXBElement<DocumentType> createDocument(DocumentType value) {
        return new JAXBElement<DocumentType>(_Document_QNAME, DocumentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FichierType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cirtil.fr/sae/commun_sommaire_et_resultat", name = "objetNumerique")
    public JAXBElement<FichierType> createObjetNumerique(FichierType value) {
        return new JAXBElement<FichierType>(_ObjetNumerique_QNAME, FichierType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ComposantDocumentVirtuelType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cirtil.fr/sae/commun_sommaire_et_resultat", name = "composant")
    public JAXBElement<ComposantDocumentVirtuelType> createComposant(ComposantDocumentVirtuelType value) {
        return new JAXBElement<ComposantDocumentVirtuelType>(_Composant_QNAME, ComposantDocumentVirtuelType.class, null, value);
    }

}
