//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.30 at 10:59:29 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.cirtil.fr/saeIntegration/referentielMetadonnees", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package fr.urssaf.image.sae.integration.ihmweb.modele.refmeta;
