#!/bin/bash

# Suppression des fichiers de log des traitements de masse qui ont plus de 10 jours
find /hawai/logs/@PROJECT_NAME@/ -name 'sae_services_executable*.log' -mtime +10 | xargs rm -f

# Redemarrage de l'ordonnanceur du GED
service @PROJECT_NAME@-ordonnanceur restart

