/*
 ################# SUPPRESSIONDES TABLES TRACES ######################
*/
DROP TABLE tracedestinatairecql;

DROP TABLE tracejournalevtcql;

DROP TABLE tracejournalevtindexcql;

DROP TABLE traceregsecuritecql;

DROP TABLE traceregtechniquecql;

DROP TABLE traceregexploitationcql;
  
DROP TABLE traceregexploitationindexcql;

DROP TABLE traceregtechniqueindexcql;

DROP TABLE traceregsecuriteindexcql;
