package sae.integration.webservice.modele;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2020-10-19T10:25:15.926+02:00
 * Generated source version: 3.3.2
 *
 */
@WebServiceClient(name = "SaeService",
                  wsdlLocation = "file:/C:/projets/java/sae/sae_trunk/sae-integration/sae-integration-test/src/test/resources/SaeService_WSDL/SaeService.wsdl",
                  targetNamespace = "http://www.cirtil.fr/saeService")
// CHECKSTYLE:OFF
@SuppressWarnings("all")
public class SaeService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.cirtil.fr/saeService", "SaeService");
    public final static QName SaeServicePort = new QName("http://www.cirtil.fr/saeService", "SaeServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/projets/java/sae/sae_trunk/sae-integration/sae-integration-test/src/test/resources/SaeService_WSDL/SaeService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SaeService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/projets/java/sae/sae_trunk/sae-integration/sae-integration-test/src/test/resources/SaeService_WSDL/SaeService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SaeService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SaeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SaeService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public SaeService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SaeService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SaeService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns SaeServicePortType
     */
    @WebEndpoint(name = "SaeServicePort")
    public SaeServicePortType getSaeServicePort() {
        return super.getPort(SaeServicePort, SaeServicePortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SaeServicePortType
     */
    @WebEndpoint(name = "SaeServicePort")
    public SaeServicePortType getSaeServicePort(WebServiceFeature... features) {
        return super.getPort(SaeServicePort, SaeServicePortType.class, features);
    }

}
