//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.19 at 02:36:29 PM CEST 
//


package fr.urssaf.image.sae.integration.droits.modele.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="issuer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="viduree" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="pagms" type="{http://www.cirtil.fr/saeIntegration/droit}ListePagmType"/>
 *         &lt;element name="cnPki" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="verifCnCert" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="cnCert" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CsType", propOrder = {
    "issuer",
    "code",
    "description",
    "viduree",
    "pagms",
    "cnPki",
    "verifCnCert",
    "cnCert"
})
// CHECKSTYLE:OFF
@SuppressWarnings("all")
public class CsType {

    @XmlElement(required = true)
    protected String issuer;
    @XmlElement(required = true)
    protected String code;
    @XmlElement(required = true)
    protected String description;
    protected long viduree;
    @XmlElement(required = true)
    protected ListePagmType pagms;
    @XmlElement(required = true)
    protected String cnPki;
    protected boolean verifCnCert;
    @XmlElement(required = true)
    protected String cnCert;

    /**
     * Gets the value of the issuer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssuer() {
        return issuer;
    }

    /**
     * Sets the value of the issuer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssuer(String value) {
        this.issuer = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the viduree property.
     * 
     */
    public long getViduree() {
        return viduree;
    }

    /**
     * Sets the value of the viduree property.
     * 
     */
    public void setViduree(long value) {
        this.viduree = value;
    }

    /**
     * Gets the value of the pagms property.
     * 
     * @return
     *     possible object is
     *     {@link ListePagmType }
     *     
     */
    public ListePagmType getPagms() {
        return pagms;
    }

    /**
     * Sets the value of the pagms property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListePagmType }
     *     
     */
    public void setPagms(ListePagmType value) {
        this.pagms = value;
    }

    /**
     * Gets the value of the cnPki property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCnPki() {
        return cnPki;
    }

    /**
     * Sets the value of the cnPki property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCnPki(String value) {
        this.cnPki = value;
    }

    /**
     * Gets the value of the verifCnCert property.
     * 
     */
    public boolean isVerifCnCert() {
        return verifCnCert;
    }

    /**
     * Sets the value of the verifCnCert property.
     * 
     */
    public void setVerifCnCert(boolean value) {
        this.verifCnCert = value;
    }

    /**
     * Gets the value of the cnCert property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCnCert() {
        return cnCert;
    }

    /**
     * Sets the value of the cnCert property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCnCert(String value) {
        this.cnCert = value;
    }

}
